### ISSUE TITLE
[Bug]: The unwrap module check returns a wrong flag

### ISSUE THREAD

**Issue by mirzaees** [isce-framework/dolphin#128]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Unwrapping does not start because of a wrong check flag, I think following should be true:

https://github.com/isce-framework/dolphin/blob/895a2b51ce4f4d7412569fff9b3b64143c7ed385/src/dolphin/workflows/stitch_and_unwrap.py#L14

### What did you expect?

I expected it would continue unwrapping because all dependencies are installed

### Reproducible steps

```bash
just running dolphin:
`dolphin run dolphin_config.yaml`
```

### Environment

```bash
Please paste the output of the following:
`python -c "import dolphin; print(dolphin.show_versions())"`
...
dolphin info:
     dolphin: 0.4.0.post1.dev0+g6e5b504.d20230908
       isce3: 0.14.0
     compass: 0.5.0

System:
      python: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
  executable: /home/smirzaee/new_setup/mambaforge/envs/opera/bin/python
     machine: Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28

Python deps:
       numpy: 1.24.4
       numba: 0.57.1
  osgeo.gdal: 3.7.0
        h5py: 3.9.0
 ruamel_yaml: None
    pydantic: 2.3.0
  setuptools: 68.1.2
None
```

**Comment by scottstanie** [comment]
oi, thanks Sara. 
Got rid of that entirely in #127 , so that should be up now in version 0.4.1
