### ISSUE TITLE
Set up the "regrow connected components" function within `snaphu-py` to run after goldstein/interpolation unwrapping

### ISSUE THREAD

**Issue by scottstanie** [isce-framework/dolphin#259]
If we've smoothed out the interferogram that we unwrapped, the conncomps won't be very useful. We should call the "regrow" after transferring the ambiguity numbers onto the original phase.

**Comment by gmgunter** [comment]
Good idea.

Right now, the [`regrow_conncomp_from_unw()`](https://github.com/isce-framework/snaphu-py/blob/82369a5d7cbf091448ab83422216ac1afda4a4bb/src/snaphu/_unwrap.py#L259) function in snaphu-py that does this is non-public and has a pretty low-level interface. I'll look into adding a public `grow_conncomps()` wrapper function with a more high-level, user-friendly interface that we can use here.

**Comment by gmgunter** [comment]
>I'll look into adding a public `grow_conncomps()` wrapper function with a more high-level, user-friendly interface that we can use here.

This has now been added in https://github.com/isce-framework/snaphu-py/pull/55
