### ISSUE TITLE
Add NetCDF support for troposphere

### ISSUE THREAD

**Issue by mirzaees** [isce-framework/dolphin#269]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

The NetCDF products for troposphere (mainly HRES data) were supported through RAiDER package which is currently crashing. 

### Describe the feature request

We need to have a better general support to handle both NetCDF and GRIB formats

**Comment by scottstanie** [comment]
Is this completed now @mirzaees ?

**Comment by scottstanie** [comment]
Closed in #337
