### ISSUE TITLE
Add metadata to compressed SLCs

### ISSUE THREAD

**Issue by mirzaees** [isce-framework/dolphin#285]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Related problems

For baseline computations, the orbital metadata related to reference date is required. Also in the tropospheric corrections, some metadata is read from the CSLCs which could be contained in the compressed CSLCs as well to make the code easier, for example:
https://github.com/mirzaees/dolphin/blob/f4b47e2ea40e4d02d74466fc1c78a29a5f98e7f1/src/dolphin/atmosphere/troposphere.py#L142

### Describe the feature request

We can generate the compressed SLCs in .h5 or .nc format instead of GeoTIF from the beginning to include metadata.

**Comment by scottstanie** [comment]
Closed in favor of disp-s1 making the HDF5 https://github.com/opera-adt/disp-s1/pull/103 , keeps dolphin more agnostic to the specific requirements on the input SLC format
